### PR TITLE
cool pr

### PR DESCRIPTION
**Pull request by Tr1NgleDev**
# Change-Log (for both Pojlib AND Wrapper):
- File downloading rewritten in C using libcURL. (pojlib)
- Better async code. (wrapper)
- Tabs > Spaces. (wrapper)
- Turned on Static Batching on QCWorld. (wrapper)
- A basic download/install progress bar. (pojlib x wrapper)
- Better keyboard handling. (wrapper)
- Now also shows the size of the file being downloaded. (pojlib x wrapper)
- Some other little changes. (pojlib x wrapper)

# Reasons for da changes (the same order):
- Java's networking for some reason is bullshit on the Quest and wouldn't let me download any files, resulting in a deadlock before the scene even gets to load (since it tries to download supportedVersions.json). This was being fixed by connecting to a VPN (i'm russian), which is kinda weird. So i just rewritten it with libcURL in the JNI C code.
- The async code was garbage (lightly speaking). Especially the web requests "async". Please don't ever do web requests like that.
- This is just the truth. Also it's harder to make spacing mistakes when you don't use spaces lol.
- Small optimization.
- CAD asked me if i could try to do it. And so i did. Makes it way easier to see when it's going to finish the download.
- self explanatory
- Downloading AmongUs.exe 69.42MB/420.69MB (haha im so funny)
- ඞඞඞඞඞ

gonna now make a pr for the Pojlib rq

### CODE REVIEW

**Comment by Tr1NgleDev** [comment]
oh i also made the keyboard handler better

**Comment by Tr1NgleDev** [comment]
https://github.com/QuestCraftPlusPlus/Pojlib/pull/47

**Review by Flopgop — COMMENTED** [review]
This is a stupid change, tabs are not the default in most editors and this benefits no one. It only introduces issues with future PRs that will most definitely be misformatted since no editor defaults to tabs. Any sane editor will automatically handle spacing issues and, if not, with a push of a button.

**Comment by Flopgop** [comment]
Also, your commit messages are atrocious, I can't tell what any of these commits change without manually sorting through each one. This is terrible git etiquette.

**Comment by paypay-a** [comment]
gawd damm even my git commit titles are better than these. anyways @thejudge156 idk if you wanna close this pull request or not

**Comment by Tr1NgleDev** [comment]
when i was doing the commits i didnt have much time to think about what exactly i changed and how to title those changes. and usually those changes are small, they arent like rewrites of any function.

**Comment by Tr1NgleDev** [comment]
again, never seen any editor default to spaces. and i did this change from spaces to tabs because there were a lot of problems with the spaces. in some places there were 2 spaces, in some 2 times 4 spaces. tabs are easier to handle. and most ides i have seen, if they dont default to tabs, then they will switch to tabs if most of the file uses tabs.

**Comment by thejudge156** [comment]
See my discord ping for information.

**Pull request closed without merging**
